# Generated by Django 4.0.1 on 2022-02-18 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_photo_remove_profile_horoscope_remove_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_handles',
            new_name='instagram_url',
        ),
    ]
