# Generated by Django 4.0.1 on 2022-02-18 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_social_handles_profile_instagram_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instagram_url',
            new_name='social_handles',
        ),
    ]
