# Generated by Django 4.0.1 on 2022-02-18 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0007_rename_instagram_url_profile_social_handles'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscope',
            name='text',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='horoscope',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
