# Generated by Django 4.0.1 on 2022-04-15 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_horoscope_text_alter_horoscope_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Horoscope',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
